import BlogArticleLayout from '../BlogArticleLayout'
import type { ComponentBlogPostDocument } from '../blog-types'
import { byohpRawSummary } from '../manual-post-summaries'

const thoughts = [
  `BYOHP: BASICALLY A SILENT DISCO STYLE EVENT WHERE WE DON'T NEED TO RENT EXPENSIVE SOUND EQUIPMENT AND STILL PLAY TO A CROWD. ALL WE NEED IS A DECK, A LAPTOP, AND CORDS. THE DJ SHOWS UP AND DOES THEIR THING. WE USE MIXCLOUD TO STREAM THE SHOW. EVERYONE BRINGS THEIR OWN HEADPHONES. THEY GET TO SET THE VOLUME TO WHATEVER FEELS COMFORTABLE FOR THEM.`,
  `PHILOSOPHY: PLAN EVENTS AROUND AREAS AND BUSINESSES THAT NEED THE MOST HELP SO THAT WHILE ENJOYING THE SPACE THAT'S FREE, THE PEOPLE THAT SHOW UP CAN BUY FOOD, DRINKS, GOODS, AND SERVICES FROM THE PEOPLE THAT WE SCHEDULE OUR EVENT AROUND.`,
  `THE EVENTS WE RUN ARE FREE BUT WE SETUP A VERY VISIBLE WAY TO ACCEPT CASH TIPS THROUGH VENMO, CASH APP BY THE DOOR. WE HAVE 3-4 THINGS THAT PEOPLE CAN GIVE MONEY TO IN PRIORITY ORDER: THE DJ, A CAUSE WE BELIEVE IN LIKE A THERAPY NONPROFIT, AND THE ORGANIZER. PROFIT AND HAVE FUN. MY FAVORITE STEP.`,
  `BONUS: WE GET A VJ TO SETUP A VISUAL SHOW FOR US. WE HAVE VR HEADSETS TO USE FOR FREE BUT WE HIGHLY ENCOURAGE PEOPLE TO DONATE IF THEY USE IT. PROFIT.`,
  `ORGANIZE THE EVENTS NEAR BUSINESSES THAT NEED MONEY. TACO TRUCKS. FOOD STANDS WITH REALLY GOOD FOOD BUT NOT A LOT OF CUSTOMERS. PEOPLE NATURALLY BUY FOOD AND DRINKS AT OUR EVENTS. HELP OUR LOCAL COMMUNITY MAKE MONEY AND STAY AFLOAT.`,
  `SCHEDULE AS MANY EVENTS AS WE WANT TO DO. INVITE FRIENDS AND MEMBERS OF OUR COMMUNITY. ENGAGE WITH PEOPLE. MAKE NEW FRIENDS. NETWORK. BIGGEST THING IS I WANT THESE EVENTS TO HAPPEN ALL OVER NASHVILLE NO MATTER THE ORGANIZER. NO MATTER THE DJ. WE JUST WANT MORE PARTIES TO HAPPEN ALL OVER THE PLACE.`,
  `START AT PRIMITIVE. ASK TREY IF HE'S OKAY HOSTING A MINI DANCEFLOOR AT PRIMITIVE. ASK DJ SEIZURE IF HE'D BE DOWN TO EXPERIMENT WITH ME. COMMUNITY DRIVEN EVENTS. MIXCLOUD. BRING YOUR OWN HEADPHONES.`,
  `CREATE NFC TAGS FOR: 1) PAYING THE DJ 2) SUPPORT A LOCAL CAUSE 3) SUPPORT A CAUSE I BELIEVE IN LIKE HAMPTON HOUSE AS A NONPROFIT TO DIRECT FUNDS TOWARDS 4) SUPPORT THE ORGANIZER. CASH TIPS: VENMO, ZELLE, CASH APP. CREATE A SIGN OF NFCS FOR SOMEONE TO JUST AS EASILY TAP TO PAY. USE THE NFC TAGS THAT YOU HAVE NOW. SELL NFC TAGS. PROFIT.`,
  `MOST IMPORTANT THING IS I DON'T WANT THE DJ TO OVERWORK THEMSELVES. I'D WANT TO SET SOMETHING UP WEEKLY, BUT IF THAT'S NOT REALISTIC FOR THEIR SCHEDULE, I TOTALLY UNDERSTAND. I DO GENUINELY WANT TO GET THEM PAID. JUST TRYING TO COME UP WITH DIFFERENT CREATIVE WAYS TO DO THAT EITHER THROUGH SPONSORSHIP OR IF I PAID THEM DIRECTLY IN ACTUAL DOLLARS EVENTUALLY. JUST NEED TO DO THE EXPERIMENT AND SEE IF IT'LL WORK FIRST.`,
  `PIE IN THE SKY DREAM: THERE'S A VERSION OF THIS WHERE I'D HIRE THE DJ FULL TIME, GIVE THEM A LIVING SALARY ($70K+) AND JUST HAVE THEM PLAY AT EVENTS I ORGANIZE ALL OVER. THAT'S THE LONG GAME. THAT'S THE GOAL.`,
  `SAME IDEA APPLIES TO MOVIES AND VIDEO GAMES. SLIGHTLY DIFFERENT FORMAT BUT SAME CORE PHILOSOPHY. EVENTS THAT ARE FREE OR CHEAP, TIPS REPLACE TICKETS, COMMUNITY IS THE PRODUCT. BUILD IT EVERYWHERE.`,
  `THE WHOLE POINT IS SIMPLE. IF YOU PLAN EVENTS WHERE PEOPLE ACTUALLY WANT TO BE, AND YOU MAKE IT EASY TO GIVE, PEOPLE WILL GIVE. BUILD COMMUNITY. SUPPORT LOCAL. PAY ARTISTS. FUND THERAPY. ALL FROM ONE FREE EVENT.`,
] as const

function BYOHPRawArticle() {
  return (
    <BlogArticleLayout post={byohpRawSummary}>
      <section id="raw-thoughts" className="scroll-mt-28">
        <ul>
          {thoughts.map((thought) => (
            <li key={thought.slice(0, 40)}>{thought}</li>
          ))}
        </ul>
      </section>
    </BlogArticleLayout>
  )
}

export const byohpRawDocument: ComponentBlogPostDocument = {
  ...byohpRawSummary,
  kind: 'component',
  Component: BYOHPRawArticle,
}
