import BlogArticleLayout from '../BlogArticleLayout'
import type { ComponentBlogPostDocument } from '../blog-types'
import { cityBuilderRawSummary } from '../manual-post-summaries'

const thoughts = [
  `VIDEO GAME APPS THAT FEEL LIKE A GAME BUT ACTUALLY DOES PROFESSIONAL WORK (CONSTRUCTION, LOGISTICS)`,
  `CONNECT CITY SKYLINE DATA / CREATE CITY BUILDER GAME AND ADD A VOTING SYSTEM FOR PEOPLE DESIGNING THE BEST CITY. MOST EFFICIENT CITY. TRAFFIC EASE. MOST ACCESSIBLE. EQUITABLE. METRICS. ANALYSIS ON TRAFFIC FLOWS. CROWD MANAGEMENT. PURCHASING LAND AGREEMENTS. PUBLIC SUPPORT.`,
  `REAL WORLD VOTING ONLY. PEOPLE LIVING IN THE CITY. REGISTER YOUR DRIVER'S LICENSE. CRYPTO VOTING SYSTEM. LET PUBLIC COMMENTERS POST INTO A FORUM AND THE COMMENTS ARE SHOWED WITHIN THE GAME AS ACTUAL COMMENTS FROM ACTUAL PEOPLE. THEY HAVE TO BE FROM THE CITY THAT THEY LIVE IN. BE ABLE TO COMMENT AND VOTE.`,
  `[VERIFYING IDENTITY THROUGH GETTING DRIVER'S LICENSE CAN BE A TURN OFF FOR SOME PEOPLE]`,
  `I THINK THE GOAL (IF WE WERE ABLE TO MAKE IT HAPPEN) IS TO MAKE GAMES THAT IS PRACTICALLY SO CHEAP FOR ANY ONE TO PLAY. WE'RE GATHERING DATA AS PEOPLE PLAY THE GAME (NOT DATA ABOUT THE PEOPLE THEMSELVES BUT HOW THEY'RE PLAYING THE GAME) AND NOW OUR REVENUE MODEL IS BASED ON THE ACTUAL PROFESSIONALS, ACTUAL CITY PLANNING DEPARTMENTS, THAT DRIVE THE VALUE IN THE DATA THAT WE GATHER AND BECOME OUR LONG TERM CUSTOMERS THAT SUBSIDIZE THE COST OF THE GAME FOR THE PEOPLE THAT ARE PLAYING THE GAME`,
  `ALSO CROWDSOURCING DESIGN WORK WHERE ANYONE CAN DO IT IS A VERY FUNDAMENTAL SHIFT IN HOW WE DO THAT, AND THERE IS A VERY REAL PATH IN NOT ONLY MAKING IT HAPPEN BUT MAKING THE DESIGNS AND ITERATING ON THEM SO THAT THE VERSION OF A PLAN THAT AN ACTUAL PROFESSIONAL SEES FOR THE FIRST TIME IS SOMETHING THAT'S SOMEWHAT USABLE FOR THEIR ACTUAL DAY TO DAY WORK`,
  `NO ADS EITHER. $10 PER PLAYER. CITY FUNDS THE GAME DEVELOPMENT. OH WAIT. GOAL OF THE GAME IN TALIHO CONTEXT IS NOW WE'RE SELLING THE SOFTWARE FOR CITY PLANNERS TO DO THEIR ACTUAL JOB`,
  `PLAY ON "EASY" MODE TO REDUCE THE NUMBER OF VARIABLES LIKE UTILITIES, TRAFFIC, WEATHER, ETC. THE PRICE OF THE GAME IS DICTATED NOT BY OUR NEED TO CHARGE THE CONSUMER. THE VALUE IS DRIVEN BY THE ACTUAL USE THAT CITIES ALL OVER THE WORLD DERIVE FROM IT. METRICS AND ANALYTICS DRIVEN GOALS WITHIN THE GAME`,
  `REAL WORLD PATH ON HOW TO TAKE TALIHO FROM A SAAS TO A GAME DEVELOPMENT COMPANY: TALIHO CREATES ENGINE TO BUILD SOFTWARE FOR CONSTRUCTION COMPANIES. 100 DEVS PROVIDES TRAINING FOR PEOPLE WHO WANT TO LEARN SOFTWARE ENGINEERING FOR FREE. WE GIVE 100 DEVS THE REPEATABLE AND ACTIONABLE KNOWLEDGE ON HOW TO LEVERAGE OPENCLAW AND THE CURRENT STATE OF AI TO THEIR BENEFIT FOR FREE`,
  `TALIHO HIRES 100 DEVS GRADS WHO WENT THROUGH THE SOFTWARE ENGINEERING (WEB APP) CURRICULUM AND THE OPENCLAW (JERRY) CURRICULUM. TALIHO DESIGNATES 1 DEDICATED SOFTWARE ENGINEER (OR MORE IF THEY NEED IT) PER COMPANY AS AN IN-HOUSE SOFTWARE ENGINEER THAT IS PAID BY TALIHO THAT IS DEDICATED IN JUST TAKING CARE OF ALL OF THE SOFTWARE DEVELOPMENT, SOFTWARE MAINTENANCE, EXISTING SCATTERED TOOL INTEGRATIONS AND CONNECTIONS, AND AUTOMATION IMPLEMENTATION FOR THAT ONE COMPANY AS A PREMIUM SERVICE THAT TALIHO OFFERS`,
  `$$$ PROFIT $$$`,
  `WE FIND SOFTWARE ENGINEERS THAT WORK FOR TALIHO THAT WANT TO BE GAME DEVELOPERS (MARIAM) AND START LEARNING GAME DEVELOPMENT. WE TRY TO MAKE OUR FIRST GAME: PLAYGROUND DESIGN SIMULATOR / CITY PARK DESIGN SIMULATOR [OR EQUIVALENT]`,
  `WE MAKE NETWORKING CONNECTIONS ON FINDING REAL WORLD PLAYGROUND DESIGNERS OR CITY PARK DESIGNERS AND GET THEIR FEEDBACK ON WHAT IT TAKES TO MAKE A "SOFTWARE" THAT IS GOOD FOR THE PROFESSIONAL JOB THAT THEY DO DAY TO DAY. THE TWIST IS THAT WE'RE ACTUALLY MAKING A VIDEO GAME THAT WE'RE CALLING THEIR "SOFTWARE" FOR THEIR PROFESSIONAL JOB`,
  `WE (MARIAM) ITERATE AND LEARN HOW TO MAKE A GREAT VIDEO GAME IN GENERAL. IV STUDIO (BOARD GAME COMPANY) HELPS IN LETTING US KNOW WHAT MAKES A GOOD GAME / HOW TO DO A SOLID KICKSTARTER / HOW TO MARKET A GAME WELL`,
  `STEP 1: I NEED TO MAKE A MARKETING WEBSITE FOR IT. STEP 2: KICKSTARTER LAUNCH. STEP 3: BUILD A PLAYGROUND DESIGN SIMULATOR GAME. STEP 4: BUILD A BRIDGE DESIGN SIMULATOR GAME. STEP 5: BUILD A CITY PLANNER SIMULATOR GAME`,
  `WE LAUNCH A MARKETING WEBSITE TO LET THE PEOPLE KNOW THE GRAND VISION OF WHAT WE'RE TRYING TO ACHIEVE (CITY PLANNER SIMULATOR). WE CREATE A KICKSTARTER PAGE TO GATHER FUNDS TO DEVELOP THIS FIRST GAME. WE PAY ACTUAL 100 DEVS GRADUATES / TALIHO SWES TO HELP US MAKE THIS GAME A REALITY`,
  `WE RELEASE OUR FIRST GAME. WE TAKE WHAT WE LEARNED FROM THAT FIRST GAME AND SEE WHAT WORKED/SEE WHAT DIDN'T AND TAKE THOSE LESSONS INTO GAME 2: BRIDGE DESIGN SIMULATOR [OR EQUIVALENT]. REPEAT THE PROCESS. $$$ PROFIT $$$`,
  `WE START WORKING ON CITY PLANNER SIMULATOR. REPEAT THE PROCESS. $$$ PROFIT $$$`,
  `GOTTA TALK TO LEON TO HELP WITH THE DEVELOPMENT`,
] as const

function CityBuilderRawArticle() {
  return (
    <BlogArticleLayout post={cityBuilderRawSummary}>
      <section id="raw-thoughts" className="scroll-mt-28">
        <ul>
          {thoughts.map((thought) => (
            <li key={thought.slice(0, 40)}>{thought}</li>
          ))}
        </ul>
      </section>
    </BlogArticleLayout>
  )
}

export const cityBuilderRawDocument: ComponentBlogPostDocument = {
  ...cityBuilderRawSummary,
  kind: 'component',
  Component: CityBuilderRawArticle,
}
