import BlogArticleLayout from '../BlogArticleLayout'
import type { BlogPost } from '../blog-types'

const thoughts = [
  `OUR BRAINS ARE REALLY GOOD AT DREAMING OF NEW AND NOVEL WAYS TO MAKE THE WORLD BETTER, AI HELPS ITERATE ON THOSE IDEAS`,
  `HOW WE CAN PREDICT THE FUTURE: MAKE LOGICAL STEPS WITH THE INFORMATION THAT WE HAVE TODAY WITH THE EVIDENCE THAT WE HAVE, MAKE SMALL EASILY DEFENDIBLE CONCLUSIONS, AND EVENTUALLY LEAD TO A WORLD THAT SEEMED IMPOSSIBLE`,
  `WHAT I THINK WILL HAPPEN: WE'RE HEADED TOWARDS A WORLD WHERE ANYONE AND EVERYONE WILL CREATE CONTENT. THE BUSINESS THAT WILL THRIVE THE MOST ARE THE ONES THAT CAN PROVIDE THE BEST OF THE BEST BY CURATING OUR TOP FAVORITE THINGS IN THINGS THAT WE THINK ARE REALLY GOOD`,
  `DEMOCRITIZATION OF GOODS. WE PAY FOR THE THINGS WE LIKE. DOLLARS ARE LIKE OUR VOTES IN REWARDING WHAT WE LIKE TO SPEND OUR TIME ON`,
  `CONTENT IS NOW CHEAP SO IT'S UP TO THE PEOPLE WHO CAN MAKE A REALLY GOOD QUALITY GAME/VIDEO/BOOK/MEDIA TO CURATE WHAT PEOPLE SHOULD SEE AND INSPIRE PEOPLE TO WORK ON THE THINGS THAT THEY LIKE`,
  `INCORPORATE THE TOOLS THAT PEOPLE USE TODAY TO ACTUALLY DRIVE AUTOMATIONS INSTEAD OF FORCING PEOPLE TO "UPSKILL" OR "LEARN NEW TRADES" IF THEY DON'T ENJOY HAVING TO LEARN A NEW FUNDAMENTAL SET OF KNOWLEDGE THAT SEEMS SCARY TO LEARN ABOUT`,
  `THERE'S A VERY REAL PATH TO THE REALITY WHERE PEOPLE ARE USING CRYPTO CURRENCIES INSTEAD OF DOLLARS TO EXCHANGE VALUES BETWEEN TRANSACTIONS BETWEEN DIFFERENT PEOPLE WHERE DEMOCRATIZING ASSETS IS NOW THE GOAL OF THE WHOLE WORLD WHERE PEOPLE WHO OWN THE DOLLAR WILL NO LONGER BE IN CONTROL AND PEOPLE WHO OWN "ASSETS" NO LONGER DRIVE THE MAIN CONVERSATION OF WHAT MAKES PEOPLE HAPPY. IF PEOPLE AREN'T DRIVEN BY FAME, FORTUNE, AND WEALTH, PEOPLE ARE DRIVEN TOWARDS WHAT MAKES THEM FEEL GOOD. ON A HIGHER PLANE, PEOPLE ARE DRIVEN TOWARDS WHAT MAKES THEM FEEL REAL EMOTIONS`,
  `IF THERE IS A REALITY WHERE EVERYONE IS HAPPY AND HEALTHY AND FREE AND EQUITABLE WHERE THE INJUSTICES OF THE WORLD ARE CORRECTED BY THE ACTUAL WORK THAT WE DO DAY TO DAY WHERE YOU CAN SEE THE DIRECT IMPACT OF WHAT YOU'RE DOING FOR THE PEOPLE WHO MOST NEED IT, PEOPLE WILL RESULT BEING HAPPIER`,
  `WE'RE HEADED TOWARDS A WORLD WHERE EVENTS ARE THE DRIVING FACTOR OF CONVERSATION. CONVERSATIONS ARE WHAT LEAD TO REAL WORLD CONNECTIONS. REAL WORLD CONNECTIONS ARE WHAT DRIVE PEOPLE TO TO WANT TO HELP EACH OTHER.`,
  `WE WANT TO INSPIRE PEOPLE TO BE DRIVEN TO MAKE REAL WORLD CHANGES, TO SOLVE THE ACTUAL PROBLEMS THAT THEY'RE SEEING DAY TO DAY, NOT THE ONES THEY SEE ON TV THAT THEY DON'T HAVE A REMOTE SENSE OF HOW TO SOLVE OR JUST FEELING DEPRESSED WITHOUT BEING ABLE TO ACT ON IT.`,
  `EVENTS IN GAMES ARE WHAT PLAY INSPIRES. SPARKING NEW EVENTS FOR PEOPLE JUST TO "PLAY" INSPIRES US IN WAYS THAT WE CAN'T IMAGINE. WHERE IT ONLY FEELS LIKE IT'S CREATIVE PROBLEM SOLVING BECAUSE YOU'RE BEING ENTERTAINED BY IT WHEN IN REALITY, YOU ARE LEARNING SOMETHING ABOUT YOURSELF, SOMETHING ABOUT THE GAME, AND SOMETHING ABOUT THE OTHER PEOPLE THAT YOU'RE PLAYING WITH THAT FUNDAMENTALY SHIFTS YOUR PERSPECTIVE IN HIDDEN WAYS THAT ARE HARD TO VISUALIZE, SEE REAL WORLD APPLICATIONS`,
  `LEARNING JAPANESE IS REALLY HARD. WATCHING RANKING OF KINGS AND CHAINSAW MAN: REZE ARC IS REALLY EASY. WHEN I WATCH SOMETHING FOR THE FIRST TIME, I WANT TO ENJOY IT FIRST BY UNDERSTANDING WHAT IS ACTUALLY HAPPENING IN THE SCREEN BY READING THE WORDS AT THE BOTTOM OF THE SCREEN. IF I LIKE IT ENOUGH, IM GOING TO WATCH IT AGAIN. AND AGAIN. AND AGAIN. AND EVERY TIME I WATCH IT AGAIN, I'M CHALLENGING MYSELF TO PLAY A NEW GAME. WHERE EVERY ONCE IN A WHILE, I STOP LOOKING AT THE CAPTIONS AND REPEAT EVERYTHING THAT THEY SAY ON SCREEN IN A HUSHED VOICE. EVERY TIME I'M PLAYING A NEW GAME, I'M PLAYING A PUZZLE WITH MYSELF. WORD PUZZLES. I LIKE WORD PUZZLES. HUH. IF I TURN OFF THE PART OF MY BRAIN THAT WANTS TO STARE AT THE WORDS FOR A LITTLE BIT, I LEARN SOMETHING ABOUT THE EMOTIONS THAT I FEEL AND THE PICTURES THAT I'M SEEING ON THE SCREEN WHERE IT'S NOT IMPORTANT FOR ME TO UNDERSTAND THE SPECIFIC WORDS RIGHT NOW. I JUST NEED TO UNDERSTAND THE SOUND, HOW TO SAY IT, AND WHAT EMOTION I FELT. MY CURIOSITY WILL NATURALLY LEAD ME TOWARDS REMEMBERING A SOUND THAT I MADE EARLIER A FEW TIMES ALREADY WHERE NOW, OH, I'M JUST NATURALLY CURIOUS WHY I'M SAYING THIS WORD SO OFTEN SO I'M GONNA LOOK UP WHAT THAT WORD MEANS. AND MY VOCABULARY HAS GROWN EVER SO SLIGHTLY. BUT I DO THIS A FEW MORE TIMES. AND AGAIN. AND AGAIN. AND EVENTUALLY, THE CONVERSATION THAT I'M ABLE TO HAVE WITH ANOTHER PERSON WHO CAN ONLY SPEAK THAT LANGUAGE IS GROWING EVER SO SLIGHTLY BY THE DAY. AND EVENTUALLY, I BECOME FLUENT IN IT ENOUGH THAT I CAN HAVE BETTER CONVERSATIONS ABOUT THING WITH OTHER PEOPLE WHO SPEAK THE SAME LANGUAGE. HIGHER ORDERS OF THINKING. WORK RELATED TALK. COMPLEX EMOTIONS. THE SAME CAN BE SAID ABOUT GAMES AND MOVIES WHERE NOW THE "LANGUAGE" THAT WE'RE SPEAKING IS STILL TECHNICALLY ENGLISH, BUT IF I'M A BEGINNER AT A GAME AND SOMEONE ELSE IS A MASTER, HOW DO I TALK TO THEM WHERE WE ACTUALLY UNDERSTAND EACH OTHER IN WHAT WE'RE TRYING TO DO? OR WHEN I WATCH A SERIES AND I WANT TO TALK ABOUT IT WITH SOMEONE. HOW DO I TALK TO THEM ABOUT IT WITHOUT BREAKING SPOILERS. YOU DON'T. WE WANT EQUITY. NO SPOILERS HERE PLEASE. INJUSTICE. THEY NEED TO "EDUCATE" THEMSELVES IN WATCHING A SHOW SO THAT WE CAN HAVE A CONVERSATION ABOUT IT LATER. NOT TODAY. EVERYONE TAKES THEIR OWN TIME. BE PATIENT. KIND. LOVING. TO ALL OTHER PEOPLE.`,
  `WAR GAMES => BOARD GAMES => VIDEO GAMES => HOW DO WE PLAY A VIDEO GAME TO END ALL WARS. TO END HUNGER. TO END INJUSTICES THAT PEOPLE ARE SEEING ALL OVER THE WORLD`,
  `ITERATION IS AT EVERY STEP OF THE PROCESS. WE CAN NOW ITERATE SO CHEAPLY THE IDEAS OF THE THINGS THAT WE WANT TO MAKE. MORE VIDEOS. BETTER GAMES. CURATED CONTENT. 1X COST FOR ITERATING ON IDEAS, 10X COST FOR ITERATING ON PLANNING/DEVELOPING, 100X COST FOR ITERATING ON IMPLEMENTATION/CHANGE ORDERS`,
] as const

function RawThoughtsArticle() {
  return (
    <BlogArticleLayout post={rawThoughtsPost}>
      <section id="raw-thoughts" className="scroll-mt-28">
        <ul>
          {thoughts.map((thought) => (
            <li key={thought.slice(0, 40)}>{thought}</li>
          ))}
        </ul>
      </section>
    </BlogArticleLayout>
  )
}

export const rawThoughtsPost: BlogPost = {
  slug: 'raw-thoughts',
  title: '* [RAW THOUGHTS]',
  summary:
    'Unfiltered notes on AI, curation, play, automation, crypto, events, language learning, and building futures worth living in.',
  teaser:
    'Raw, unedited stream of consciousness on the forces shaping how we create, connect, and play.',
  strapline: 'Unfiltered signal. No polish. All conviction.',
  publishedAt: '2026-03-08',
  publishedLabel: 'March 8, 2026',
  readTime: '6 min read',
  category: 'Raw Thoughts',
  tags: ['AI', 'Curation', 'Play', 'Crypto', 'Events', 'Language'],
  quote:
    "Content is now cheap so it's up to the people who can make really good quality to curate what people should see.",
  stats: [
    {
      label: 'Read',
      value: '6 minutes',
    },
    {
      label: 'Mode',
      value: 'Raw notes',
    },
    {
      label: 'Thread',
      value: 'Unfiltered conviction',
    },
  ],
  signals: [
    {
      title: 'AI accelerates ideation',
      text: 'Our brains dream up futures; AI helps iterate on those ideas faster than ever before.',
    },
    {
      title: 'Curation over creation',
      text: 'When content is cheap, the real value is in curating and surfacing what matters most.',
    },
    {
      title: 'Play as a learning engine',
      text: 'Games and media teach us about ourselves and others in ways that feel like entertainment.',
    },
    {
      title: 'Events drive connection',
      text: 'Real world events spark conversations that lead to genuine human connections and care.',
    },
  ],
  sectionLinks: [
    {
      id: 'raw-thoughts',
      label: 'Raw thoughts',
    },
  ],
  Component: RawThoughtsArticle,
}
