import BlogArticleLayout from '../BlogArticleLayout'
import type { ComponentBlogPostDocument } from '../blog-types'
import { gameNightsRawSummary } from '../manual-post-summaries'

const thoughts = [
  `APPLY THE BYOHP MODEL TO VIDEO GAMES. GAME NIGHTS. LAN PARTIES. FIND A LARGE ENOUGH SPACE TO HOST GROUP VIDEO GAMING SESSIONS. BRING YOUR OWN CONSOLE. PLAN THESE ON A FREQUENT BASIS. BUILD COMMUNITY.`,
  `FIND LARGE SPACES FOR GROUP GAMING SESSIONS. WAREHOUSES. COMMUNITY CENTERS. SOMEONE'S GARAGE. A CHURCH BASEMENT. LITERALLY ANYWHERE WITH OUTLETS AND ENOUGH SPACE FOR PEOPLE TO SET UP NEXT TO EACH OTHER.`,
  `BRING YOUR OWN CONSOLE. BYOC. LAN PARTY STYLE. OLD SCHOOL BUT IT WORKS. PEOPLE BRING WHAT THEY HAVE. SWITCHES. PLAYSTATIONS. XBOXES. STEAM DECKS. LAPTOPS. WHATEVER. THE HARDWARE DOESN'T MATTER. THE PEOPLE DO.`,
  `PLAN ON A FREQUENT BASIS. WEEKLY. BIWEEKLY. THE FREQUENCY IS WHAT MAKES IT REAL. A ONE-TIME EVENT IS JUST A HANGOUT. A RECURRING EVENT IS A COMMUNITY. SHOW UP ENOUGH TIMES AND STRANGERS BECOME FRIENDS.`,
  `IN-PERSON GAMING HITS DIFFERENT THAN ONLINE. YOU CAN SEE SOMEONE'S FACE WHEN THEY LOSE. YOU CAN HIGH-FIVE WHEN YOU WIN. YOU CAN TRASH TALK SOMEONE WHO IS SITTING RIGHT NEXT TO YOU AND THEN SHARE A PIZZA WITH THEM FIVE MINUTES LATER. THAT IS REAL CONNECTION.`,
  `GAMES TEACH COMMUNICATION. STRATEGY. TEAMWORK. PATIENCE. ALL THE THINGS WE NEED MORE OF IN THE WORLD. AND THEY TEACH IT WITHOUT ANYONE FEELING LIKE THEY'RE BEING TAUGHT. THAT'S THE MAGIC. PLAY IS THE BEST TEACHER.`,
  `SAME PHILOSOPHY AS BYOHP AND MOVIE EVENTS. THE EVENT IS FREE OR CHEAP. NO BARRIERS. NO GATEKEEPING. JUST SHOW UP WITH YOUR CONTROLLER AND BE READY TO HAVE A GOOD TIME.`,
  `THE BARRIER TO ENTRY IS LOW. YOU NEED A SPACE AND SOME POWER STRIPS. MAYBE A FOLDING TABLE OR TWO. EVERYTHING ELSE PEOPLE BRING THEMSELVES. THE INFRASTRUCTURE IS MINIMAL. THE COMMUNITY IMPACT IS MASSIVE.`,
  `REGULAR SESSIONS TURN STRANGERS INTO TEAMMATES INTO FRIENDS INTO COMMUNITY. THAT COMPOUNDING EFFECT IS REAL. EVERY SESSION BUILDS ON THE LAST ONE. INSIDE JOKES. RIVALRIES. TRADITIONS. ALL THE THINGS THAT MAKE A GROUP OF PEOPLE FEEL LIKE THEY BELONG TOGETHER.`,
] as const

function GameNightsRawArticle() {
  return (
    <BlogArticleLayout post={gameNightsRawSummary}>
      <section id="raw-thoughts" className="scroll-mt-28">
        <ul>
          {thoughts.map((thought) => (
            <li key={thought.slice(0, 40)}>{thought}</li>
          ))}
        </ul>
      </section>
    </BlogArticleLayout>
  )
}

export const gameNightsRawDocument: ComponentBlogPostDocument = {
  ...gameNightsRawSummary,
  kind: 'component',
  Component: GameNightsRawArticle,
}
