import BlogArticleLayout from '../BlogArticleLayout'
import type { ComponentBlogPostDocument } from '../blog-types'
import { movieEventsRawSummary } from '../manual-post-summaries'

const thoughts = [
  `APPLY THE BYOHP MODEL TO MOVIES. GO TO THE THEATER TO BRING MY OWN MOVIE TO WATCH. EVENT DRIVEN REVENUE MODEL FOR AMC OR REGAL SO THAT I CAN TAKE MY FRIENDS TO WATCH SHREK ON A TUESDAY NIGHT AS A FUN GROUP ACTIVITY WHERE WE HAVE THE THEATER ROOM TO OURSELVES AND INVITE AS MANY OF OUR FRIENDS AS WE WANT.`,
  `ASK REGAL IF THEY'D LET US RENT A THEATER AND HOW MUCH. GREAT IF THEY ALLOW US. INVITE ALL MY FRIENDS TO WATCH A MOVIE THAT WE VOTE ON. CHEERIOCRACY. EVERYONE GETS A SAY IN WHAT WE WATCH. THE MOST POPULAR PICK WINS. DEMOCRACY BUT FUN.`,
  `SETUP CASH, VENMO, ZELLE, CASH APP TIPS TO HELP PAY FOR THE THEATER RENTAL THROUGH AN NFC CARD OR QR CODE. SAME MODEL AS THE BYOHP EVENTS. NO ONE IS FORCED TO PAY A FIXED PRICE. EVERYONE CONTRIBUTES WHAT THEY CAN. THE GROUP ABSORBS THE COST TOGETHER.`,
  `THE MOVIE IS JUST THE EXCUSE. THE REAL VALUE IS SITTING NEXT TO PEOPLE YOU CARE ABOUT AND SHARING AN EXPERIENCE TOGETHER. LAUGHING AT THE SAME JOKES. GASPING AT THE SAME PLOT TWISTS. QUOTING THE SAME LINES FOR WEEKS AFTER.`,
  `DO THIS ON A REGULAR BASIS. WEEKLY. BIWEEKLY. MONTHLY. WHATEVER WORKS. THE FREQUENCY IS WHAT TURNS A HANGOUT INTO A TRADITION. A TRADITION INTO A COMMUNITY. A COMMUNITY INTO SOMETHING REAL.`,
  `BUILD COMMUNITY AROUND SHARED STORIES. SHARED REFERENCES. INSIDE JOKES FROM THE MOVIES YOU WATCH TOGETHER. NOW YOU HAVE SOMETHING TO TALK ABOUT THAT'S YOURS. NOT SOMETHING FROM TWITTER. NOT SOMETHING FROM THE NEWS. YOURS.`,
  `THE VOTING PART IS ACTUALLY REALLY FUN. PEOPLE CAMPAIGN FOR THEIR MOVIE. THEY MAKE CASES. THEY DEBATE. THEY LOBBY. AND THEN EVERYONE LAUGHS ABOUT THE OUTCOME. THE VOTE ITSELF BECOMES A BONDING MOMENT BEFORE THE MOVIE EVEN STARTS.`,
  `SAME PHILOSOPHY AS EVERYTHING ELSE. EVENTS THAT ARE FREE OR CHEAP. TIPS REPLACE TICKETS. NOBODY IS PRICED OUT. EVERYBODY BELONGS. THE THEATER GETS REVENUE ON A SLOW NIGHT. WE GET A PRIVATE ROOM. EVERYONE WINS.`,
] as const

function MovieEventsRawArticle() {
  return (
    <BlogArticleLayout post={movieEventsRawSummary}>
      <section id="raw-thoughts" className="scroll-mt-28">
        <ul>
          {thoughts.map((thought) => (
            <li key={thought.slice(0, 40)}>{thought}</li>
          ))}
        </ul>
      </section>
    </BlogArticleLayout>
  )
}

export const movieEventsRawDocument: ComponentBlogPostDocument = {
  ...movieEventsRawSummary,
  kind: 'component',
  Component: MovieEventsRawArticle,
}
